"""Initial migration

Revision ID: 307a622107d1
Revises: 
Create Date: 2025-02-06 05:06:59.431551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '307a622107d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if 'id' column already exists in 'pokemon' table
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [column['name'] for column in inspector.get_columns('pokemon')]

    if 'id' not in columns:
        with op.batch_alter_table('pokemon', schema=None) as batch_op:
            batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
            batch_op.create_index(batch_op.f('ix_pokemon_id'), ['id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.drop_constraint('user_pokemon_pokemon_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pokemon', ['pokemon_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_pokemon_pokemon_id_fkey', 'pokemon', ['pokemon_id'], ['number'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pokemon_id'))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
